export class RouterConsts {
  static readonly AddGroupPage = 'AddGroupPage';
  static readonly PrivacyPage = 'PrivacyPage';
  static readonly AboutPage = 'AboutPage';
  static readonly PlayerPage = 'PlayerPage';
  static readonly SeasonDetailPage = 'SeasonDetailPage';
  static readonly VideoDetailPage = 'VideoDetailPage';
  static readonly VideoListPage = 'VideoListPage';
  static readonly FavoriteListPage = 'FavoriteListPage';
  static readonly ColorModePage = 'ColorModePage';
}