export class RouterConsts {
  static readonly SplashPage = 'SplashPage'
  static readonly IndexPage = 'IndexPage'
  static readonly AddGroupPage = 'AddGroupPage';
  static readonly PrivacyPage = 'PrivacyPage';
  static readonly AboutPage = 'AboutPage';
  static readonly PlayerPage = 'PlayerPage';
  static readonly SeasonDetailPage = 'SeasonDetailPage';
  static readonly VideoDetailPage = 'VideoDetailPage';
  static readonly VideoListPage = 'VideoListPage';
  static readonly FavoriteListPage = 'FavoriteListPage';
  static readonly ColorModePage = 'ColorModePage';
  static readonly PlayerEnginePage = 'PlayerEnginePage';
  static readonly AccountPage = 'AccountPage';
  static readonly AddAccountPage = 'AddAccountPage';
  static readonly WebITongPage = 'WebITongPage';
  static readonly SearchPage = 'SearchPage';
  static readonly CastDetailPage = 'CastDetailPage';
  static readonly LiveTvChannelListPage = 'LiveTvChannelListPage'
  static readonly LiveTvPage = 'LiveTvPage'
  static readonly MinePage = 'MinePage'
  static readonly ServerDiscoveryPage = 'ServerDiscoveryPage'

}
